# preload = ~/arch_setup/dotfiles/backgrounds/p2qm9ksnvi2f1.jpeg
# wallpaper = , ~/arch_setup/dotfiles/backgrounds/p2qm9ksnvi2f1.jpeg
wallpaper {
    monitor =
    path = ~/arch_setup/dotfiles/backgrounds/yosemite.png
    # path = ~/arch_setup/dotfiles/backgrounds/p2qm9ksnvi2f1.jpeg
    # path = ~/arch_setup/dotfiles/backgrounds/mountain-sunrise2.jpg
    fit_mode = cover
    timeout = 36000
}
splash = false
