# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

source = ~/.config/hypr/mocha.conf
source = ~/.config/hypr/hyprland.d/environment.conf
source = ~/.config/hypr/hyprland.d/monitors.conf
# source = ~/.config/hypr/hyprland.d/noctalia_shell.conf
source = ~/.config/hypr/hyprland.d/autostart.conf
source = ~/.config/hypr/hyprland.d/permissions.conf
source = ~/.config/hypr/hyprland.d/look_and_feel.conf
source = ~/.config/hypr/hyprland.d/input.conf
source = ~/.config/hypr/hyprland.d/keybindings.conf
source = ~/.config/hypr/hyprland.d/rules.conf
source = ~/.config/hypr/hyprland.d/animations.conf
source = ~/.config/hypr/hyprland.d/misc.conf
source = ~/.config/hypr/hyprland.d/layouts.conf

