#!/usr/bin/env zsh

# echo '.zshenv loaded'

export EDITOR=nvim
export VISUAL=nvim

# # Добавляем директории в PATH
# typeset -U path
# path=(~/.local/bin ~/bin $path)
# export PATH
# path=(~/.dotnet/tools $path)
# export PATH
export DOTNET_TOOLS='~/.dotnet/tools'
export LOCAL_BIN="${HOME}/.local/bin"
