#!/usr/bin/env zsh

# echo '.zshenv loaded'

export EDITOR=nvim
export VISUAL=nvim

# # Добавляем директории в PATH
typeset -U path
# path=(~/.local/bin ~/bin $path)
# export PATH
# path=(~/.dotnet/tools $path)
# export PATH
DOTNET_ROOT="${HOME}/.dotnet/sdk"
DOTNET_TOOLS="${HOME}/.dotnet/tools"
LOCAL_BIN="${HOME}/.local/bin"

export DOTNET_ROOT
path=($LOCAL_BIN $DOTNET_ROOT $DOTNET_TOOLS $path)
