#!/usr/bin/env zsh

# echo '.zshrc loaded'

autoload -U edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

# Инициализация автодополнения
autoload -Uz compinit && compinit

# Инициализация prompt
autoload -Uz promptinit
promptinit
prompt walters

# История команд
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
setopt HIST_IGNORE_SPACE
setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY

# Включает игнорирование регистра при автодополнении
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

# Set up Promt
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '%b '
setopt PROMPT_SUBST
PROMPT='%F{blue}╭─%f %F{blue}%~%f %F{red}${vcs_info_msg_0_}%f$
%F{blue}╰─%f %F{green}➜%f '

RPROMPT='%F{green}%*%f'

# Setup aliaces

# Создает алиасы для ls, чтобы всегда использовать цветной вывод
alias ls='ls --color=auto'
alias ll='ls -l --color=auto'
alias la='ls -la --color=auto'
alias l='ls -CF --color=auto'

# alias nvim="NVIM_APPNAME=nvim_lazy nvim"
